# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'UTF8Example' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for UTF8Example
  pod "SNUtil",:subspecs => ['NSDictionaryArray_utf8', 'WKWebViewPost'], :path => ".../" #.表示同级；../ 表示上一级
#   pod 'SNUtil', :subspecs => ['NSDictionaryArray_utf8', 'WKWebViewPost'], :git => 'https://github.com/lizhi0123/SNSubspecTest.git', :branch => 'master'


end
