# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'UTF8Example' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for UTF8Example

pod "SNUtil",:subspecs => ['SNOrderPage', 'SNDetialPage','MGJRouter_Nav'], :path => "../" #.表示同级；../ 表示上一级
#   pod 'SNUtil', :subspecs => ['SNSubspec', 'SNDetialPage'], :git => 'https://github.com/lizhi0123/SNSubspecTest.git', :branch => 'master'
end
